### ISSUE TITLE
Origami-lib codebase is flakey

### ISSUE THREAD

**Issue by fristonio** [Cloud-CV/origami-lib#19]
There are a lot of flake8 linting errors in `origami-lib` for a better and readable codebase we should remove them.

Also I suggest using something like [yapf](https://github.com/google/yapf) for auto linting the code and adding git hook `pre_commit` to it that way it would be easy to keep the codebase from flake8 linting errors.

**Comment by uttu357** [comment]
Is this still relevant?

**Comment by fristonio** [comment]
No this is resolved in refactor branch. I think we can close this.
